title: Le Data Blog
description: >
  Un blog sur la data,<br> l'intelligence artificielle, <br>
  et mes projets.
copyright: Rémi Bois
sass:
  sass_dir: assets/sass
url: http://ledatablog.com
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 

twitter_username: "sildar44"
linkedin_username: "remi-bois"
github_username:  "sildar"
feed_icon: feed
email: "remibois.contact@gmail.com"
paginate_path: "/page/:num/"
paginate: 4
